name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.14.0"

    - name: Clean install dependencies # 단계 이름 변경
      working-directory: ./client
      run: |
        rm -rf node_modules # node_modules 폴더 삭제
        rm -f package-lock.json # package-lock.json 파일 삭제
        npm install # 종속성 다시 설치

      - name: Build project
        working-directory: ./client
        run: npm run build

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      - name: Deploy to S3
        working-directory: ./client # client 폴더로 이동
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete
